March kb articles
telerik/kendo-vue pull request #549
Opened 2024-03-26 19:09 UTC by filipKovachev

The KB articles for this month

2024-03-27 08:58 UTC, zdravkov approved these changes

2024-03-27 11:12 UTC, vveesseelliinnaa requested changes

2024-03-27 11:12 UTC, vveesseelliinnaa commented on knowledge-base/upload-custom-validation-error.md
> +This Knowledge base(KB) article demonstrates how we can add a custom validation error for the Upload component.
Should we a sentence explaining when the added custom error will be shown in the demo?

2024-03-27 11:12 UTC, vveesseelliinnaa commented on knowledge-base/examples/chart-tooltip-series-item/main.vue
This sample does not work on Stackblitz for some reason (it is OK in CodeSandBox)

2024-03-27 11:12 UTC, vveesseelliinnaa commented on knowledge-base/examples/chart-tooltip-series-item/main.vue
> +              Name: 'Approved by a very log whatnot label here sooo long',
Make sure that the long message does not contain so many typos. E.g., you can change it to 
"Approved by a very long, loooong and even longer label shown inside a tooltip"

2024-03-27 11:12 UTC, vveesseelliinnaa commented on knowledge-base/chart-tooltip-series-item.md
> +How to add a tooltip to the Chart series items?
It was not clear to me that the tooltip will be shown only when I hover over the labels in the y axis. Can you update the description to state that, so the clients will not expect them over the actual series items of the chart.

2024-10-18 14:52 UTC, vveesseelliinnaa approved these changes

2024-10-18 15:47 UTC, merged